name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - 1.14
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Start dynamodb-local
      run: |
        docker run -d -p 8000:8000 amazon/dynamodb-local

    - name: Build & Test
      run: |
        make test
      env:
        AWS_ACCESS_KEY_ID: dummy
        AWS_SECRET_ACCESS_KEY: dummy
